# Generated by Django 3.0.8 on 2020-07-13 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default=datetime.datetime(2020, 7, 13, 18, 40, 51, 956430, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
